# Generated by Django 3.2.5 on 2021-07-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc_price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.DecimalField(decimal_places=8, max_digits=25),
        ),
    ]
